# Generated by Django 3.2.8 on 2021-11-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kling_app', '0002_geeksmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
