# Generated by Django 3.2.8 on 2021-11-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kling_app', '0004_geeksmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
